# Site settings
title: Gökhan Varol
email: info@gokhanvarol.com
location:
  city: Istanbul
  country: Turkey
job_title: "Pianist, Composer, Arranger"
author:
  name: "Gökhan Varol"
  twitter: gokhan_varol
  google_plus: 107015095174650081571
logo: logo.png

baseurl: ""       # the subpath of your site, e.g. /blog
url: "https://gokhanvarol.com"     # the base hostname & protocol for your site

# dont include github readme
# exclude: ['README.md']
exclude:
  - CNAME
  - license.md
  - README.md

# plugins
gems:
  - jekyll-sitemap

# include pages
include: ['_pages']

languages:
  - name: 'TÜRKÇE'
    key: 'tr'
  - name: 'ENGLISH'
    key: 'en'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/gokhan_varol
  - title: facebook
    url: https://facebook.com/gokhan_varol
  - title: youtube
    url: https://youtube.com/gokhan_varol
  - title: instagram
    url: https://www.instagram.com/gokhan_varol
  - title: soundcloud
    url: https://soundcloud/gokhan_varol
  - title: spotify
    url: https://open.spotify.com/artist/5C4bqUMIJN2WucEthkJ0uN?si=niG8KkA3Suei3Evit2sUtQ

# Social metadata (JSON-LD)
socialmeta:
  name: Gökhan Varol
  links:
    - https://twitter.com/gokhan_varol
    - https://facebook.com/gokhan_varol
    - https://youtube.com/gokhan_varol
    - https://soundcloud/gokhan_varol
    - https://www.instagram.com/gokhan_varol/
    - https://open.spotify.com/artist/5C4bqUMIJN2WucEthkJ0uN?si=niG8KkA3Suei3Evit2sUtQ


# Build settings
markdown: kramdown
permalink: /:categories/:title

# Sass settings
sass:
    style: compressed

# Main site translations
translations:
    tr:
        nav-about: 'Hakkında'
        nav-projects: 'ÇALIŞMALAR'
        nav-contact: 'İLETİŞİM'
        date: 'Tarih'
    en:
        nav-about: 'About'
        nav-projects: 'Projects'
        nav-contact: 'Contact'
        date: 'Date'
